
# =========================
# LOCAL MONGODB (COMPASS / LOCAL SERVER)
# =========================

spring.data.mongodb.uri=mongodb+srv://gamagevipulaguna_db_user:dugiqwe1234@cluster0.bru3lj9.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=smart_campus_db
spring.data.mongodb.auto-index-creation=true
