# =========================
# MONGODB ATLAS (CLOUD)
# =========================

spring.data.mongodb.uri=mongodb+srv://gamagevipulaguna_db_user:dugiqwe1234@cluster0.bru3lj9.mongodb.net/smart_campus_db?retryWrites=true&w=majority
spring.data.mongodb.database=smart_campus_db
spring.data.mongodb.auto-index-creation=true
