
# =========================
# LOCAL MONGODB (COMPASS / LOCAL SERVER)
# =========================

spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus_db
spring.data.mongodb.database=smart_campus_db
spring.data.mongodb.auto-index-creation=true
